In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from sqlalchemy import create_engine
from sqlalchemy.engine.url import URL
import config
from config import CONNSTRING
from sklearn.model_selection import train_test_split


In [3]:
#read the data from SQL
engine= create_engine(CONNSTRING)

query = "SELECT * FROM customer_data"
df = pd.read_sql(query, engine)
        

In [5]:

null_count = df['age'].isnull().sum()
print(f'there are {null_count} null values')

there are 0 null values


In [10]:
customer_segmentation = df[['age', 'gender', 'category', 'Purchase Amount (USD)', 'location', 'season', 'Previous Purchases', 'Frequency of Purchases', 'Promo Code Used','Payment Method']].copy()
customer_segmentation_encoded = pd.get_dummies(customer_segmentation, columns=['gender','category','location','season','Frequency of Purchases','Promo Code Used','Payment Method'])
customer_segmentation_encoded.drop(['Promo Code Used_No','gender_Male'], axis=1, inplace=True)



In [11]:
customer_segmentation_encoded.head()


age  Purchase Amount (USD)  Previous Purchases  gender_Female  \
0   55                   53.0                  14          False   
1   19                   64.0                   2          False   
2   50                   73.0                  23          False   
3   21                   90.0                  49          False   
4   45                   49.0                  31          False   

   category_Accessories  category_Clothing  category_Footwear  \
0                 False               True              False   
1                 False               True              False   
2                 False               True              False   
3                 False              False               True   
4                 False               True              False   

   category_Outerwear  location_Alabama  location_Alaska  ...  \
0               False             False            False  ...   
1               False             False            False  ...   
2               False             False            False  ...   
3               False             False            False  ...   
4               False             False            False  ...   

   Frequency of Purchases_Monthly  Frequency of Purchases_Quarterly  \
0                           False                             False   
1                           False                             False   
2                           False                             False   
3                           False                             False   
4                           False                             False   

   Frequency of Purchases_Weekly  Promo Code Used_Yes  \
0                          False                 True   
1                          False                 True   
2                           True                 True   
3                           True                 True   
4                          False                 True   

   Payment Method_Bank Transfer  Payment Method_Cash  \
0                         False                False   
1                         False                 True   
2                         False                False   
3                         False                False   
4                         False                False   

   Payment Method_Credit Card  Payment Method_Debit Card  \
0                       False                      False   
1                       False                      False   
2                        True                      False   
3                       False                      False   
4                       False                      False   

   Payment Method_PayPal  Payment Method_Venmo  
0                  False                  True  
1                  False                 False  
2                  False                 False  
3                   True                 False  
4                   True                 False  

[5 rows x 76 columns]

In [12]:
X = customer_segmentation_encoded.drop('age', axis=1)
y = customer_segmentation_encoded['age']

In [16]:
#divde train and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.32, random_state=42)


In [17]:
from sklearn.ensemble import RandomForestClassifier

#create mode
model = RandomForestClassifier(random_state=42)

#fit model
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

#make predictions
y_pred = model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [1 0 1 ... 2 1 0]
 [2 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 2 1 ... 1 0 0]
 [0 3 0 ... 0 0 0]]
              precision    recall  f1-score   support

          18       0.00      0.00      0.00        31
          19       0.00      0.00      0.00        23
          20       0.00      0.00      0.00        19
          21       0.00      0.00      0.00        25
          22       0.05      0.06      0.05        18
          23       0.00      0.00      0.00        12
          24       0.00      0.00      0.00        18
          25       0.00      0.00      0.00        28
          26       0.08      0.07      0.08        27
          27       0.08      0.14      0.10        21
          28       0.00      0.00      0.00        23
          29       0.00      0.00      0.00        25
          30       0.06      0.04      0.04        27
          31       0.00      0.00      0.00        26
          32       0.00      0.00      0.00        24
          33   